AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GitProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: github.lambda_handler
      Runtime: python2.7
      Timeout: 10
      CodeUri: ./deployment.zip
      Events:
        GitMessage:
          Type: SNS
          Properties:
            Topic: !Ref 'Topic'
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Github Events
      TopicName: GithubEventTopic
