AWSTemplateFormatVersion: '2010-09-09'
Description: Sns topic for github events
Resources:
  GithubEventTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Github Events
      TopicName: GithubEventTopic
  SNSGithubPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: SNSPolicyGithub
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Join [ '', [ 'arn:aws:iam::', !Ref "AWS::AccountId", ':root' ] ]
          Action: sns:Publish
          Resource: "*"
      Topics:
      - Ref: GithubEventTopic
Outputs:
  GithubSNS:
    Description: Sns topic for github events
    Value: !GetAtt GithubEventTopic.TopicName
    Export:
      Name: GithubSNS
