
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  CredstashKey:
    Type: String
Resources:
  BuildSpawn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build_spawn.lambda_handler
      Runtime: python2.7
      Timeout: 40
      CodeUri: ../tmp/deployment.zip
      Role: !ImportValue BuildSpawnRole

  BuildDone:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build_done.lambda_handler
      Runtime: python2.7
      Timeout: 40
      CodeUri: ../tmp/deployment.zip
      Role: !ImportValue CredstashLambdaRole
      Environment:
        Variables:
          TABLE_NAME: !ImportValue EventsTable

Outputs:
  BuildSpawnLambda:
    Description: "Lambda for Build Spawn"
    Value: !Join ['', ['arn:aws:lambda:', !Ref 'AWS::Region',  ':', !Ref 'AWS::AccountId', ':function:', !Ref BuildSpawn]]
    Export:
      Name: BuildSpawnLambda

  BuildDoneLambda:
    Description: "Lambda for build done"
    Value: !Join ['', ['arn:aws:lambda:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':function:', !Ref BuildDone]]
    Export:
      Name: BuildDoneLambda
