Transform: AWS::Serverless-2016-10-31
Resources:
  BuildStarter:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build_starter.lambda_handler
      Runtime: python2.7
      Timeout: 10
      CodeUri: ../tmp/deployment.zip
      Role: !ImportValue CredstashLambdaRole
      Events:
        DynamoStream:
          Type: DynamoDB
          Properties:
            Stream: !ImportValue EventsStream
            StartingPosition: TRIM_HORIZON
      Environment:
        Variables:
          TABLE_NAME: !ImportValue EventsTable
          CODEBUILD_ROLE: !ImportValue CodebuildGenericRole
          STATE_MACHINE_ROLE: !ImportValue StateMachineRole
          BUILD_DONE_LAMBDA: !ImportValue BuildDoneLambda
          BUILD_SPAWN: !ImportValue BuildSpawnLambda
Outputs:
  BuildStarterLambda:
    Description: "Lambda for build starter"
    Value: !Join ['', ['arn:aws:lambda:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':function:', !Ref BuildStarter]]
    Export:
      Name: BuildStarterLambda
