AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EventDb:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "date_modified"
          AttributeType: "S"
        - AttributeName: "event_type"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      GlobalSecondaryIndexes:
        - IndexName: "tagLSI"
          KeySchema:
            - AttributeName: "event_type"
              KeyType: "HASH"
            - AttributeName: "date_modified"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
Outputs:
  EventsTable:
    Description: "DynamoTable for events"
    Value: !Ref EventDb
    Export:
      Name: EventsTable
  EventsStream:
    Description: "DynamoStream for events"
    Value: !GetAtt EventDb.StreamArn
    Export:
      Name: EventsStream
