# needs access to
# stepfunction:GetActivityTask
# stepfunction:SendTaskSuccess
AWSTemplateFormatVersion: '2010-09-09'
Description: "A generic codebuild job and activity for dockerhub images"
Parameters:
  CredstashKey:
    Type: String
  GithubToken:
    Type: String
Resources:
  DockerhubBuilds:
    Type: AWS::CodeBuild::Project
    Properties:
      Description: A generic codebuild job for dockerhub image building
      ServiceRole: !GetAtt CodebuildRole.Arn
      Source:
        Type: GITHUB
        Location: !Join ['', ['https://ktruckenmiller:', !Ref GithubToken, '@github.com/ktruckenmiller/docker-friend.git']]
      Artifacts:
        Type: no_artifacts
      Environment:
        Type: linuxContainer
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:1.12.1
        EnvironmentVariables:
        - Name: ORG_NAME
          Value: ktruckenmiller
        - Name: IMAGE_NAME
          Value: docker-friend
        - Name: IMAGE_TAG
          Value: latest
        - Name: DOCKERFILE_LOCATION
          Value: Dockerfile.ruby
      TimeoutInMinutes: 120
  CodebuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - 'codebuild:*'
                Resource: "*"
              # Credstash
              - Effect: "Allow"
                Action:
                  - 'kms:Decrypt'
                Resource: !Join ['', ['arn:aws:kms:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':key/', !Ref CredstashKey ]]
              - Effect: "Allow"
                Action:
                  - "dynamodb:GetItem"
                  - "dynamodb:Query"
                  - "dynamodb:Scan"
                Resource: !Join ['', ['arn:aws:dynamodb:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':table/credential-store' ]]
              - Effect: "Allow"
                Action:
                  - "stepfunction:GetActivityTask"
                  - "stepfunction:SendTaskSuccess"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
