AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ## SNS stuff
  GitTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Github Events
      TopicName: GithubEventTopic
  GitProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: github.lambda_handler
      Runtime: python2.7
      Timeout: 10
      CodeUri: ../tmp/deployment.zip
      Role: !ImportValue CredstashLambdaRole
      Policies: AmazonDynamoDBFullAccess
      Events:
        GitMessage:
          Type: SNS
          Properties:
            Topic: !Ref GitTopic
      Environment:
        Variables:
          TABLE_NAME: !ImportValue EventsTable
Outputs:
  GitTopic:
    Description: "GitTopic for git events"
    Value: !Ref GitTopic
    Export:
      Name: GithubSNSTopic
