AWSTemplateFormatVersion: "2010-09-09"
Resources:
  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "states.us-west-2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - 'lambda:InvokeFunction'
                Resource: *

Outputs:
  StateMachineRole:
    Description: "state machine role for lambdas"
    Value: !Join ['', ['arn:aws:iam::', !Ref 'AWS::AccountId', ':role/', !Ref StateMachineRole]]
    Export:
      Name: StateMachineRole
