version: 0.1
phases:
  install:
    commands:
      - env
      - echo $ACTIVITY_ARN
      - "aws stepfunctions get-activity-task --activity-arn $ACTIVITY_ARN --query \"taskToken\" | sed 's/\"//g' > task.id"
      - echo $(cat task.id)
      - echo installing credstash
      - pip install credstash
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login --username="$(credstash -r us-west-2 get dockercloud.username)" --password="$(credstash -r us-west-2 get dockercloud.password)"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - "docker build -f $DOCKERFILE_LOCATION -t $IMAGE_NAME:$TAG . && echo $? > build.txt"
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - "stat --printf='' build.txt 2>/dev/null && docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest"
      - "stat --printf='' build.txt 2>/dev/null && docker push $IMAGE_NAME:$TAG"
      - "stat --printf='' build.txt 2>/dev/null && docker push $IMAGE_NAME:latest"
  post_build:
    commands:
      - echo sending back response to state machine that we are good to go
      - "stat --printf='' build.txt 2>/dev/null || aws stepfunctions send-task-success --task-token $(cat task.id) --task-output '{\"err\": \"true\", \"tag\": \"'$TAG'\", \"repo_name\": \"'$REPO_NAME'\", \"state_machine_arn\": \"'$STATE_MACHINE_ARN'\", \"deploy_id\": \"'$DEPLOY_ID'\", \"image_name\": \"'$IMAGE_NAME'\", \"codebuild_id\": \"'$CODEBUILD_BUILD_ID'\"}'"
      - "stat --printf='' build.txt 2>/dev/null && aws stepfunctions send-task-success --task-token $(cat task.id) --task-output '{\"err\": \"false\", \"tag\": \"'$TAG'\", \"repo_name\": \"'$REPO_NAME'\", \"state_machine_arn\": \"'$STATE_MACHINE_ARN'\", \"deploy_id\": \"'$DEPLOY_ID'\", \"image_name\": \"'$IMAGE_NAME'\", \"codebuild_id\": \"'$CODEBUILD_BUILD_ID'\"}'"
